### ISSUE TITLE
Change requests for segmentio/terraform-docs

### ISSUE THREAD

**Issue by metmajer** [hashicorp/terraform-config-inspect#21]
We are currently integrating support for Terraform 0.12's HCL 2 into [terraform-docs](https://github.com/segmentio/terraform-docs) while trying our best to retain as much functionality of our existing integration with (legacy) HCL as possible via [segmentio/terraform-docs #62](https://github.com/segmentio/terraform-docs/issues/62).

Since `terraform-config-inspect` supports parsing HCL and HCL 2 configurations, it would be a very valuable integration layer for `terraform-docs` to support existing and future Terraform versions. I could see that external PRs are currently not welcome, however, you may want to consider the following changes we consider necessary to keep up support for our existing functionality:

1) ~~Reading variables in the order they are defined. This feature is used by those who create forms or Jenkins pipeline parameter lists using terraform-docs where the order of variables is important. For this, [tfconfig/module.go](https://github.com/hashicorp/terraform-config-inspect/blob/master/tfconfig/module.go#L9) would need to support an additional ordered list of variables.~~
Update: not necessary. We can derive the order from the line number reported through this library.

2) Our users make use of lead comments for modules, variables and outputs. While the latter support description fields for this purpose, some of our users have been using it to provide random metadata, such as regular expressions for validation of variables.

If those changes are accepted, we can provide pull requests for these features.

Thanks! Thoughts?

FYI @khos2ow @moatra

**Comment by metmajer** [comment]
FYI @apparentlymart

**Comment by metmajer** [comment]
@mildwonkey referring to you since you are already supporting #17 #18. Would you support our change request so we can start preparing a pull request for 2)?

**Comment by mildwonkey** [comment]
Hi @metmajer!

I believe is something that would require a change in Terraform to be useful and consistent. The tools (HCL and terraform-config-inspect) won't be able to tell an inconsequential comment (`#TODO: fix this`) from important metadata without some kind of identifier. 

One idea - and this is off the top of my head, not necessarily something I'm seriously considering - would be adding a `module` block where you could add a description, or maybe even unstructured metadata:

In a module's main.tf: 

```hcl
module "canonical_module_name" {
   description = "This module is an example"
   metadata = `{"blah":"foo"}`
}
```

Or perhaps this made-up ([yard](https://yardoc.org/guides/)-inspired) example of self-documenting code (again, an idea, not necessarily a serious suggestion):

```hcl
# @module: I am module documentation
resource "some_resource" "foo" {
  ...
}
```

I certainly like the general idea of module metadata, or some other form of self-documentation in terraform config files. Based on that, I think that this is best addressed in the terraform repository. I will leave this issue open so we don't lose track of it.

**Comment by metmajer** [comment]
@mildwonkey thanks for the quick input, much appreciated! In fact, both HCL and, according to @apparentlymart in https://github.com/hashicorp/terraform/issues/19604, HCL2's `hcl2/hclwrite` package would allow us to gather access to comments in Terraform configurations.

Being able to capture these comments alone would be already be sufficient for `terraform-doc's` users to read out those metadata information and process as needed. A client of mine would use this to auto-validate the input parameters of a Jenkins pipeline, whose parameter set is automatically created using a combination of `terraform-docs` with the `terraform_inputs_jenkins_pipeline_params` pre-commit hook in [getcloudnative/pre-commit-hooks-terraform](https://github.com/getcloudnative/pre-commit-hooks-terraform).

**Comment by metmajer** [comment]
I just had a quick look, with HCL, we're reading out comments like this: https://github.com/segmentio/terraform-docs/blob/master/internal/pkg/doc/doc.go#L193.

**Comment by metmajer** [comment]
@mildwonkey Any update on this?

**Comment by metmajer** [comment]
@mildwonkey @apparentlymart our users are already rioting because of the lack of support for Terraform 0.12. can we count on you to find a solution together? Indeed much appreciated!

**Comment by teamterraform** [comment]
Hi @metmajer! Sorry for the slow response here.

A key problem here is that comments are not considered part of the HCL 2.0 information model, and so the HCL parser throws them away. No HCL-based application treats comments as significant, and philosophically the parser is designed around the idea that comments are annotations for maintainers rather than part of the language.

As you've seen, `hclwrite` _does_ preserve them, but it does so only so that it can permit surgical changes to parts of a configuration without removing or displacing the comments. `hclwrite` just treats them as opaque, meaningless tokens and doesn't assign any special meaning to them... it just promises to carry them around as elements are moved around the configuration.

`terraform-config-inspect` is designed around Terraform's _own_ model of what modules are made of, and that doesn't include commands. Instead, it uses the `description` attributes inside certain constructs to add human-oriented annotations for the parts of a module that serve as its _public interface_, and assumes that comments are aimed at those maintaining the module and thus belong in-context inside the code, not out-of-context in some rendered documentation.

At this point, we think the path forward on this is to move this discussion over into the `hashicorp/terraform` repository and discuss there the use-cases for annotating internal constructs inside a module for use in generated documentation, and then based on those use-cases we can consider ways to meet those use-cases using proper features of the language, rather than comments, as @mildwonkey mentioned earlier. Any language features we add for this would be added in the main Terraform config decoder first, and then mimicked over here in `terraform-config-inspect` for consumption in other software.

We can see one example in the `terraform-docs` repository of what seems to be a whole-module docstring, rather than an annotation on any particular construct. If you wouldn't mind, it'd be helpful to gather any other examples of what `terraform-docs` can read and what the intended use-cases are for each thing it supports in a new issue over in `hashicorp/terraform`, and then we can continue there a discussion about what language features we might add to Terraform to allow capturing some or all of that information.

Thanks for starting this discussion, and sorry for running you around here. We want to consider any changes to the Terraform language carefully, and the `hashicorp/terraform` repository is the right place to have a discussion like that, because `terraform-config-inspect` will always just be a subset of what Terraform itself understands. Thanks!

**Comment by metmajer** [comment]
@teamterraform Thanks for sharing thoughts and what a path forward could look like. Personally, I am unsure if the Terraform community will give our demand for handling random metadata in comments to supplement the existing `description` attribute a high enough priority, but we'll give it a shot.

In the meantime, we'll also see what we can achieve given the current options. This might be the faster approach so we are able to serve our community for now.

Let me add that we treat comments entirely as "free form annotations". What `terraform-docs` users do with these data is totally up to them. An example would be the definition of a regex string so users can have Terraform module inputs automatically validated by an outside handler (e.g. an automatically generated form).

**Comment by mwarkentin** [comment]
@metmajer @teamterraform any idea if this discussion was reopened on the main tf repo anywhere?

**Comment by khos2ow** [comment]
@mwarkentin we, eventually, decided to bite the bullet and drop the support of extracting metadata in the shape of comments in .tf files in `terraform-docs`. So at this point I don't think of any discussion regarding this going on anywhere.
