### ISSUE TITLE
Feature: support local variables

### ISSUE THREAD

**Issue by howdoicomputer** [hashicorp/terraform-config-inspect#50]
Would be nice if local variables were outputted

**Comment by apparentlymart** [comment]
Hi @howdoicomputer! Sorry for the slow response.

The intended scope of this library is to expose information about the external "API" of a module, to help with generating documentation intended for consumption by _users_ of the module, rather than _maintainers_ of the module.

As we noted in the readme, we want to keep the scope of this library limited to keep manageable the maintenance work of keeping it synchronized with additions to the Terraform language, and so we don't intend to add anything outside of that scope. If you have use-cases beyond those this library is intended to solve, you can feel free to create a fork under the terms of the open source license and add additional features, although of course you will then be responsible for maintaining those additions over time if the corresponding Terraform language features change in a future release.

Thanks, and sorry again for taking so long to respond.
